algorithm_description: DPS Unit test
algorithm_name: dps-unit-test-mlucas
algorithm_version: mlucas/ogc
keywords: dps
code_repository: https://repo.dit.maap-project.org/root/dps-unit-test.git
citation: https://repo.dit.maap-project.org/root/dps-unit-test.git
author: MAAP
contributor: MAAP
release_notes: None
run_command: dps-unit-test/run-test.sh
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 20 # mebibytes

inputs:
  - name: input_file
    doc: input file
    label: input file
    type: string
    default: input/input_file.txt

outputs:
  - name: out
    type: Directory

