algorithm_description: DPS Unit test
algorithm_name: dps-unit-test-mlucas-ogc
algorithm_version: mlucas_ogc
keywords: dps, ogc
code_repository: https://github.com/MAAP-Project/dps-unit-test.git
citation: https://github.com/MAAP-Project/dps-unit-test.git
release_notes: None
run_command: dps-unit-test/run-test.sh
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 20 # mebibytes

inputs:
  - name: input_file
    doc: input file
    label: input file
    type: string
    default: input/input_file.txt

outputs:
  - name: out
    type: Directory

